### ISSUE TITLE
Routes from the profile page

### ISSUE THREAD

**Issue by azebolsky** [azebolsky/Park-Texas#1]
Once logged in via google, I would like to route to their profile page if they have already set up a profile before.  If they have not setup a profile it will take them to a page to fill out a profile.  Thanks!

**Comment by azebolsky** [comment]
Will need to route to profile when requested and if no profile has been setup to have a button to add a profile page.  Once added, the button to add a profile will disappear and their profile information will show up.

**Comment by myDeveloperJourney** [comment]
During this 1:1 we discovered that in order to dynamically route a user based on whether they have a profile or not, we'd need to create a custom piece of middleware that fires off once Google makes a request to the `/oauth2callback` route. That piece of middleware would need to check if the profile exists by either checking the profile model for the logged-in user or checking for a boolean property on `req.user`, which we could add instead
